version: "3"

services: 
  app:
    build: .
    image: flaviogf/the_password
    command: manage:app
  nginx:
    image: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
